# Generated by Django 3.0.5 on 2020-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.TextField(db_index=True)),
                ('userType', models.BooleanField(db_index=True)),
                ('pm', models.TextField(blank=True, max_length=500)),
                ('career', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
