# Generated by Django 3.0.5 on 2020-10-01 07:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.TextField(max_length=20)),
                ('userType', models.CharField(choices=[('student', '수강생'), ('teacher', '강사')], db_index=True, max_length=20)),
                ('pr', models.TextField(blank=True, max_length=500, null=True)),
                ('career', models.TextField(blank=True, max_length=500, null=True)),
            ],
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
