# Generated by Django 3.0.5 on 2020-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pm',
            new_name='pr',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(db_index=True, max_length=20),
        ),
    ]
