# Generated by Django 3.0.5 on 2020-09-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200903_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pr',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
