# Generated by Django 3.0.5 on 2020-10-01 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturelist', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturelist.Lecuture')),
                ('funding_title', models.ForeignKey(db_column='funding_title', on_delete=django.db.models.deletion.CASCADE, related_name='lectures_title', to='lecturelist.Lecuture')),
            ],
        ),
    ]
