# Generated by Django 3.0.5 on 2020-10-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('lecturelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecuture',
            name='lecture_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecuture',
            name='lecture_detail',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
