# Generated by Django 3.0.5 on 2020-10-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturelist', '0002_auto_20201001_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecuture',
            name='lecture_user',
        ),
    ]
